name: SCSS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.2

    - name: Install Node.js
      uses: actions/setup-node@v4.0.2
      
    - name: Install Sass
      run: npm install -g sass
      
    - name: Build SCSS
      run: |
        sass ./src/main.scss:./build/main.css
        sass ./src/main.scss:./build/main.min.css --style compressed
        
    - name: Archive SCSS artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: SCSS-artifacts
        path: ./build
